/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcureRouteImport } from './routes/procure'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAgentsSocialRouteImport } from './routes/api/public/agents/social'
import { Route as ApiPublicAgentsLogoRouteImport } from './routes/api/public/agents/logo'
import { Route as ApiPublicAgentsImageRouteImport } from './routes/api/public/agents/image'

const ProcureRoute = ProcureRouteImport.update({
  id: '/procure',
  path: '/procure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsSocialRoute = ApiPublicAgentsSocialRouteImport.update({
  id: '/public/agents/social',
  path: '/public/agents/social',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicAgentsLogoRoute = ApiPublicAgentsLogoRouteImport.update({
  id: '/public/agents/logo',
  path: '/public/agents/logo',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicAgentsImageRoute = ApiPublicAgentsImageRouteImport.update({
  id: '/public/agents/image',
  path: '/public/agents/image',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api': typeof ApiRouteWithChildren
  '/procure': typeof ProcureRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api': typeof ApiRouteWithChildren
  '/procure': typeof ProcureRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api': typeof ApiRouteWithChildren
  '/procure': typeof ProcureRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/api'
    | '/procure'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/api'
    | '/procure'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/api'
    | '/procure'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApiRoute: typeof ApiRouteWithChildren
  ProcureRoute: typeof ProcureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procure': {
      id: '/procure'
      path: '/procure'
      fullPath: '/procure'
      preLoaderRoute: typeof ProcureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/social': {
      id: '/api/public/agents/social'
      path: '/public/agents/social'
      fullPath: '/api/public/agents/social'
      preLoaderRoute: typeof ApiPublicAgentsSocialRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/agents/logo': {
      id: '/api/public/agents/logo'
      path: '/public/agents/logo'
      fullPath: '/api/public/agents/logo'
      preLoaderRoute: typeof ApiPublicAgentsLogoRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/agents/image': {
      id: '/api/public/agents/image'
      path: '/public/agents/image'
      fullPath: '/api/public/agents/image'
      preLoaderRoute: typeof ApiPublicAgentsImageRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiPublicAgentsImageRoute: typeof ApiPublicAgentsImageRoute
  ApiPublicAgentsLogoRoute: typeof ApiPublicAgentsLogoRoute
  ApiPublicAgentsSocialRoute: typeof ApiPublicAgentsSocialRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiPublicAgentsImageRoute: ApiPublicAgentsImageRoute,
  ApiPublicAgentsLogoRoute: ApiPublicAgentsLogoRoute,
  ApiPublicAgentsSocialRoute: ApiPublicAgentsSocialRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApiRoute: ApiRouteWithChildren,
  ProcureRoute: ProcureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
