/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcureRouteImport } from './routes/procure'
import { Route as IntegrateRouteImport } from './routes/integrate'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentCardDotjsonRouteImport } from './routes/agent-card[.]json'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiA2aRouteImport } from './routes/api/a2a'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known.agent[.]json'
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known.agent-card[.]json'
import { Route as ApiPublicAgentsSocialRouteImport } from './routes/api/public/agents/social'
import { Route as ApiPublicAgentsLogoRouteImport } from './routes/api/public/agents/logo'
import { Route as ApiPublicAgentsImageRouteImport } from './routes/api/public/agents/image'

const ProcureRoute = ProcureRouteImport.update({
  id: '/procure',
  path: '/procure',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrateRoute = IntegrateRouteImport.update({
  id: '/integrate',
  path: '/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCardDotjsonRoute = AgentCardDotjsonRouteImport.update({
  id: '/agent-card.json',
  path: '/agent-card.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA2aRoute = ApiA2aRouteImport.update({
  id: '/api/a2a',
  path: '/api/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsSocialRoute = ApiPublicAgentsSocialRouteImport.update({
  id: '/api/public/agents/social',
  path: '/api/public/agents/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsLogoRoute = ApiPublicAgentsLogoRouteImport.update({
  id: '/api/public/agents/logo',
  path: '/api/public/agents/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsImageRoute = ApiPublicAgentsImageRouteImport.update({
  id: '/api/public/agents/image',
  path: '/api/public/agents/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-card.json': typeof AgentCardDotjsonRoute
  '/agents': typeof AgentsRoute
  '/health': typeof HealthRoute
  '/integrate': typeof IntegrateRoute
  '/procure': typeof ProcureRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-card.json': typeof AgentCardDotjsonRoute
  '/agents': typeof AgentsRoute
  '/health': typeof HealthRoute
  '/integrate': typeof IntegrateRoute
  '/procure': typeof ProcureRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-card.json': typeof AgentCardDotjsonRoute
  '/agents': typeof AgentsRoute
  '/health': typeof HealthRoute
  '/integrate': typeof IntegrateRoute
  '/procure': typeof ProcureRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-card.json'
    | '/agents'
    | '/health'
    | '/integrate'
    | '/procure'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/api/a2a'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-card.json'
    | '/agents'
    | '/health'
    | '/integrate'
    | '/procure'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/api/a2a'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
  id:
    | '__root__'
    | '/'
    | '/agent-card.json'
    | '/agents'
    | '/health'
    | '/integrate'
    | '/procure'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/api/a2a'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentCardDotjsonRoute: typeof AgentCardDotjsonRoute
  AgentsRoute: typeof AgentsRoute
  HealthRoute: typeof HealthRoute
  IntegrateRoute: typeof IntegrateRoute
  ProcureRoute: typeof ProcureRoute
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  ApiA2aRoute: typeof ApiA2aRoute
  ApiPublicAgentsImageRoute: typeof ApiPublicAgentsImageRoute
  ApiPublicAgentsLogoRoute: typeof ApiPublicAgentsLogoRoute
  ApiPublicAgentsSocialRoute: typeof ApiPublicAgentsSocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procure': {
      id: '/procure'
      path: '/procure'
      fullPath: '/procure'
      preLoaderRoute: typeof ProcureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrate': {
      id: '/integrate'
      path: '/integrate'
      fullPath: '/integrate'
      preLoaderRoute: typeof IntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-card.json': {
      id: '/agent-card.json'
      path: '/agent-card.json'
      fullPath: '/agent-card.json'
      preLoaderRoute: typeof AgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a2a': {
      id: '/api/a2a'
      path: '/api/a2a'
      fullPath: '/api/a2a'
      preLoaderRoute: typeof ApiA2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json'
      path: '/.well-known/agent-card.json'
      fullPath: '/.well-known/agent-card.json'
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/social': {
      id: '/api/public/agents/social'
      path: '/api/public/agents/social'
      fullPath: '/api/public/agents/social'
      preLoaderRoute: typeof ApiPublicAgentsSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/logo': {
      id: '/api/public/agents/logo'
      path: '/api/public/agents/logo'
      fullPath: '/api/public/agents/logo'
      preLoaderRoute: typeof ApiPublicAgentsLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/image': {
      id: '/api/public/agents/image'
      path: '/api/public/agents/image'
      fullPath: '/api/public/agents/image'
      preLoaderRoute: typeof ApiPublicAgentsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentCardDotjsonRoute: AgentCardDotjsonRoute,
  AgentsRoute: AgentsRoute,
  HealthRoute: HealthRoute,
  IntegrateRoute: IntegrateRoute,
  ProcureRoute: ProcureRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  ApiA2aRoute: ApiA2aRoute,
  ApiPublicAgentsImageRoute: ApiPublicAgentsImageRoute,
  ApiPublicAgentsLogoRoute: ApiPublicAgentsLogoRoute,
  ApiPublicAgentsSocialRoute: ApiPublicAgentsSocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
