/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProcureRouteImport } from './routes/procure'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IntegrateRouteImport } from './routes/integrate'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentCardDotjsonRouteImport } from './routes/agent-card[.]json'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiA2aRouteImport } from './routes/api/a2a'
import { Route as DotwellKnownAgentsDotjsonRouteImport } from './routes/[.]well-known.agents[.]json'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known.agent[.]json'
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known.agent-card[.]json'
import { Route as ApiPublicJobsIndexRouteImport } from './routes/api/public/jobs/index'
import { Route as ApiPublicJobsJobIdRouteImport } from './routes/api/public/jobs/$jobId'
import { Route as ApiPublicAgentsSocialRouteImport } from './routes/api/public/agents/social'
import { Route as ApiPublicAgentsLogoRouteImport } from './routes/api/public/agents/logo'
import { Route as ApiPublicAgentsImageRouteImport } from './routes/api/public/agents/image'
import { Route as ApiPublicAgentsCategoryRouteImport } from './routes/api/public/agents/$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcureRoute = ProcureRouteImport.update({
  id: '/procure',
  path: '/procure',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrateRoute = IntegrateRouteImport.update({
  id: '/integrate',
  path: '/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCardDotjsonRoute = AgentCardDotjsonRouteImport.update({
  id: '/agent-card.json',
  path: '/agent-card.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA2aRoute = ApiA2aRouteImport.update({
  id: '/api/a2a',
  path: '/api/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentsDotjsonRoute =
  DotwellKnownAgentsDotjsonRouteImport.update({
    id: '/.well-known/agents.json',
    path: '/.well-known/agents.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsIndexRoute = ApiPublicJobsIndexRouteImport.update({
  id: '/api/public/jobs/',
  path: '/api/public/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsJobIdRoute = ApiPublicJobsJobIdRouteImport.update({
  id: '/api/public/jobs/$jobId',
  path: '/api/public/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsSocialRoute = ApiPublicAgentsSocialRouteImport.update({
  id: '/api/public/agents/social',
  path: '/api/public/agents/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsLogoRoute = ApiPublicAgentsLogoRouteImport.update({
  id: '/api/public/agents/logo',
  path: '/api/public/agents/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsImageRoute = ApiPublicAgentsImageRouteImport.update({
  id: '/api/public/agents/image',
  path: '/api/public/agents/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsCategoryRoute = ApiPublicAgentsCategoryRouteImport.update({
  id: '/api/public/agents/$category',
  path: '/api/public/agents/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-card.json': typeof AgentCardDotjsonRoute
  '/agents': typeof AgentsRoute
  '/health': typeof HealthRoute
  '/integrate': typeof IntegrateRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/procure': typeof ProcureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agents.json': typeof DotwellKnownAgentsDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/public/agents/$category': typeof ApiPublicAgentsCategoryRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
  '/api/public/jobs/$jobId': typeof ApiPublicJobsJobIdRoute
  '/api/public/jobs/': typeof ApiPublicJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-card.json': typeof AgentCardDotjsonRoute
  '/agents': typeof AgentsRoute
  '/health': typeof HealthRoute
  '/integrate': typeof IntegrateRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/procure': typeof ProcureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agents.json': typeof DotwellKnownAgentsDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/public/agents/$category': typeof ApiPublicAgentsCategoryRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
  '/api/public/jobs/$jobId': typeof ApiPublicJobsJobIdRoute
  '/api/public/jobs': typeof ApiPublicJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-card.json': typeof AgentCardDotjsonRoute
  '/agents': typeof AgentsRoute
  '/health': typeof HealthRoute
  '/integrate': typeof IntegrateRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/procure': typeof ProcureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agents.json': typeof DotwellKnownAgentsDotjsonRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/public/agents/$category': typeof ApiPublicAgentsCategoryRoute
  '/api/public/agents/image': typeof ApiPublicAgentsImageRoute
  '/api/public/agents/logo': typeof ApiPublicAgentsLogoRoute
  '/api/public/agents/social': typeof ApiPublicAgentsSocialRoute
  '/api/public/jobs/$jobId': typeof ApiPublicJobsJobIdRoute
  '/api/public/jobs/': typeof ApiPublicJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-card.json'
    | '/agents'
    | '/health'
    | '/integrate'
    | '/llms.txt'
    | '/openapi.json'
    | '/procure'
    | '/sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/agents.json'
    | '/api/a2a'
    | '/api/public/agents/$category'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
    | '/api/public/jobs/$jobId'
    | '/api/public/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-card.json'
    | '/agents'
    | '/health'
    | '/integrate'
    | '/llms.txt'
    | '/openapi.json'
    | '/procure'
    | '/sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/agents.json'
    | '/api/a2a'
    | '/api/public/agents/$category'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
    | '/api/public/jobs/$jobId'
    | '/api/public/jobs'
  id:
    | '__root__'
    | '/'
    | '/agent-card.json'
    | '/agents'
    | '/health'
    | '/integrate'
    | '/llms.txt'
    | '/openapi.json'
    | '/procure'
    | '/sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/agents.json'
    | '/api/a2a'
    | '/api/public/agents/$category'
    | '/api/public/agents/image'
    | '/api/public/agents/logo'
    | '/api/public/agents/social'
    | '/api/public/jobs/$jobId'
    | '/api/public/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentCardDotjsonRoute: typeof AgentCardDotjsonRoute
  AgentsRoute: typeof AgentsRoute
  HealthRoute: typeof HealthRoute
  IntegrateRoute: typeof IntegrateRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  ProcureRoute: typeof ProcureRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  DotwellKnownAgentsDotjsonRoute: typeof DotwellKnownAgentsDotjsonRoute
  ApiA2aRoute: typeof ApiA2aRoute
  ApiPublicAgentsCategoryRoute: typeof ApiPublicAgentsCategoryRoute
  ApiPublicAgentsImageRoute: typeof ApiPublicAgentsImageRoute
  ApiPublicAgentsLogoRoute: typeof ApiPublicAgentsLogoRoute
  ApiPublicAgentsSocialRoute: typeof ApiPublicAgentsSocialRoute
  ApiPublicJobsJobIdRoute: typeof ApiPublicJobsJobIdRoute
  ApiPublicJobsIndexRoute: typeof ApiPublicJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procure': {
      id: '/procure'
      path: '/procure'
      fullPath: '/procure'
      preLoaderRoute: typeof ProcureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrate': {
      id: '/integrate'
      path: '/integrate'
      fullPath: '/integrate'
      preLoaderRoute: typeof IntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-card.json': {
      id: '/agent-card.json'
      path: '/agent-card.json'
      fullPath: '/agent-card.json'
      preLoaderRoute: typeof AgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a2a': {
      id: '/api/a2a'
      path: '/api/a2a'
      fullPath: '/api/a2a'
      preLoaderRoute: typeof ApiA2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agents.json': {
      id: '/.well-known/agents.json'
      path: '/.well-known/agents.json'
      fullPath: '/.well-known/agents.json'
      preLoaderRoute: typeof DotwellKnownAgentsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json'
      path: '/.well-known/agent-card.json'
      fullPath: '/.well-known/agent-card.json'
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/': {
      id: '/api/public/jobs/'
      path: '/api/public/jobs'
      fullPath: '/api/public/jobs/'
      preLoaderRoute: typeof ApiPublicJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/$jobId': {
      id: '/api/public/jobs/$jobId'
      path: '/api/public/jobs/$jobId'
      fullPath: '/api/public/jobs/$jobId'
      preLoaderRoute: typeof ApiPublicJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/social': {
      id: '/api/public/agents/social'
      path: '/api/public/agents/social'
      fullPath: '/api/public/agents/social'
      preLoaderRoute: typeof ApiPublicAgentsSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/logo': {
      id: '/api/public/agents/logo'
      path: '/api/public/agents/logo'
      fullPath: '/api/public/agents/logo'
      preLoaderRoute: typeof ApiPublicAgentsLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/image': {
      id: '/api/public/agents/image'
      path: '/api/public/agents/image'
      fullPath: '/api/public/agents/image'
      preLoaderRoute: typeof ApiPublicAgentsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/$category': {
      id: '/api/public/agents/$category'
      path: '/api/public/agents/$category'
      fullPath: '/api/public/agents/$category'
      preLoaderRoute: typeof ApiPublicAgentsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentCardDotjsonRoute: AgentCardDotjsonRoute,
  AgentsRoute: AgentsRoute,
  HealthRoute: HealthRoute,
  IntegrateRoute: IntegrateRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  ProcureRoute: ProcureRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  DotwellKnownAgentsDotjsonRoute: DotwellKnownAgentsDotjsonRoute,
  ApiA2aRoute: ApiA2aRoute,
  ApiPublicAgentsCategoryRoute: ApiPublicAgentsCategoryRoute,
  ApiPublicAgentsImageRoute: ApiPublicAgentsImageRoute,
  ApiPublicAgentsLogoRoute: ApiPublicAgentsLogoRoute,
  ApiPublicAgentsSocialRoute: ApiPublicAgentsSocialRoute,
  ApiPublicJobsJobIdRoute: ApiPublicJobsJobIdRoute,
  ApiPublicJobsIndexRoute: ApiPublicJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
